### ISSUE TITLE
GTDB Database Download: RecursionError: maximum recursion depth exceeded while pickling an object

### ISSUE THREAD

**Issue by PeterCx** [leylabmpi/Struo2#39]
Hi there,

Thanks for this great tool. I am trying to download the GTDB 207 database following the [tutorial](https://github.com/leylabmpi/Struo2/wiki/GTDB-database-download-and-usage). I plan to update the database after adding my own MAGs and then classify with Kraken2.

I am running into an error with the first command which I am unable to solve.

Command: ./util_scripts/database_download.py -t 30 -r 207 -d kraken2 metadata taxdump phylogeny -- custom_dbs

Output:
2023-01-18 10:19:52,823 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,159 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2 HTTP/1.1" 301 275
2023-01-18 10:19:53,196 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/ HTTP/1.1" 200 5235
2023-01-18 10:19:53,310 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,310 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,312 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,313 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,313 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,314 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,315 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,315 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,317 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,318 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,319 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,386 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/hash.k2d HTTP/1.1" 200 308038999800
2023-01-18 10:19:53,391 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/library.md5 HTTP/1.1" 200 49
2023-01-18 10:19:53,394 - File written: custom_dbs/GTDB_release207/kraken2/library.md5
2023-01-18 10:19:53,398 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database_mers.md5 HTTP/1.1" 200 480
2023-01-18 10:19:53,400 - File written: custom_dbs/GTDB_release207/kraken2/database_mers.md5
2023-01-18 10:19:53,427 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database250mers.kmer_distrib HTTP/1.1" 200 8803861
2023-01-18 10:19:53,436 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/k2d.md5 HTTP/1.1" 200 129
2023-01-18 10:19:53,438 - File written: custom_dbs/GTDB_release207/kraken2/k2d.md5
2023-01-18 10:19:53,453 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database200mers.kmer_distrib HTTP/1.1" 200 9703154
2023-01-18 10:19:53,462 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database150mers.kmer_distrib HTTP/1.1" 200 10771937
2023-01-18 10:19:53,489 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database200mers.kraken HTTP/1.1" 200 580405087
2023-01-18 10:19:53,502 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database250mers.kraken HTTP/1.1" 200 568175580
2023-01-18 10:19:53,504 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/library.tar.gz HTTP/1.1" 200 62268566241
2023-01-18 10:19:53,523 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/database150mers.kraken HTTP/1.1" 200 605871315
2023-01-18 10:19:53,603 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:19:53,672 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/library.tar.gz HTTP/1.1" 200 62268566241
2023-01-18 10:19:58,174 - File written: custom_dbs/GTDB_release207/kraken2/database200mers.kmer_distrib
2023-01-18 10:19:58,314 - File written: custom_dbs/GTDB_release207/kraken2/database250mers.kmer_distrib
2023-01-18 10:20:00,179 - Starting new HTTP connection (1): ftp.tue.mpg.de:80
2023-01-18 10:20:00,249 - http://ftp.tue.mpg.de:80 "GET /ebio/projects/struo2/GTDB_release207/kraken2/hash.k2d HTTP/1.1" 200 308038999800
2023-01-18 10:20:00,650 - File written: custom_dbs/GTDB_release207/kraken2/database150mers.kmer_distrib
2023-01-18 10:23:45,623 - File written: custom_dbs/GTDB_release207/kraken2/database250mers.kraken
2023-01-18 10:23:51,984 - File written: custom_dbs/GTDB_release207/kraken2/database200mers.kraken
2023-01-18 10:24:12,125 - File written: custom_dbs/GTDB_release207/kraken2/database150mers.kraken
2023-01-18 12:11:36,527 - File written: custom_dbs/GTDB_release207/kraken2/library.tar.gz
2023-01-18 17:09:49,298 - File written: custom_dbs/GTDB_release207/kraken2/hash.k2d
Traceback (most recent call last):
  File "/workspace/pot/peterc/Equine/Struo2/./util_scripts/database_download.py", line 144, in <module>
    main(args)
  File "/workspace/pot/peterc/Equine/Struo2/./util_scripts/database_download.py", line 138, in main
    dl_files(args.base_url, release, db,
  File "/workspace/pot/peterc/Equine/Struo2/./util_scripts/database_download.py", line 121, in dl_files
    pool.map(func, bs4_list)
  File "/home/peterc/miniconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/peterc/miniconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/peterc/miniconda3/lib/python3.9/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/home/peterc/miniconda3/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/peterc/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
**RecursionError: maximum recursion depth exceeded while pickling an object**

Not sure what to do. Your help is greatly appreciated.

Kind regards,

Peter

**Comment by PeterCx** [comment]
I am not sure what this error is. However, the database seems to have downloaded in its entirety. I proceeded with the subsequent steps and was able to classify no problem. This tool is fantastic btw. Many thanks

**Comment by nick-youngblut** [comment]
This error has been reported previously: https://github.com/leylabmpi/Struo2/issues/16

I looked into the issue but haven't found a good solution. I might have to switch to a differ python package for file downloading.

Good luck with your analyzes!

**Comment by PeterCx** [comment]
Ah ok apologies. Never seen the previous post. Thanks

**Comment by nick-youngblut** [comment]
FYI: I've increased the max recursion allowed for `database_download.py`, so hopefully that fixes the issue
